name: Audit

on:
  schedule:
    - cron: 56 11 * * WED

jobs:
  pnpm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: pnpm
      - run: pnpm audit
